INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('jicama',17,15,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('potatoes',20,82,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('water chestnuts',5,74,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('gelatin',22,77,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('leeks',1,83,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('squid',11,67,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('caviar',20,91,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('radishes',11,91,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('chutney',17,92,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('cornstarch',4,32,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('halibut',5,27,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('liver',9,87,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('marshmallows',4,20,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('ale',21,90,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('Parmesan cheese',24,99,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('grouper',18,25,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('celery seeds',11,1,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('oatmeal',4,89,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('tomato sauce',7,29,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('pickles',24,6,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('borscht',24,14,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('tea',23,93,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('salsa',12,89,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('cucumbers',23,33,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('corn flour',9,22,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('plum tomatoes',16,85,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('chili sauce',16,59,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('pico de gallo',11,49,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('pomegranates',13,41,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('almond extract',2,62,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('cherries',10,40,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('habanero chilies',19,62,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('fennel seeds',11,54,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('pepper',5,66,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('breadfruit',6,57,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('lentils',24,1,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('guavas',20,66,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('creme fraiche',13,51,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('chipotle peppers',6,48,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('broth',9,55,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('venison',21,13,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('cocoa powder',12,33,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('anchovy paste',1,41,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('sazon',22,78,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('wine vinegar',17,77,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('couscous',21,4,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('bard',19,68,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('summer squash',23,64,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('fennel',12,9,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('asiago cheese',17,82,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('steak',3,92,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('brazil nuts',16,6,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('cream of tartar',5,41,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('prunes',7,23,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('andouille sausage',7,20,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('curry paste',12,21,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('coconuts',18,65,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('raisins',3,52,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('Havarti cheese',18,56,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('broccoli raab',15,98,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('cinnamon',18,69,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('mint',15,35,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('bruschetta',12,22,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('kiwi',14,57,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('kumquats',4,57,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('tartar sauce',9,12,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('rhubarb',1,58,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('hot sauce',22,7,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('dumpling',6,43,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('poppy seeds',17,50,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('dried leeks',23,43,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('bean threads',18,10,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('aquavit',24,79,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('crabs',5,48,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('shitakes',9,22,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('blue cheese',4,30,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('mesclun greens',9,28,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('green beans',5,89,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('mascarpone',5,55,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('thyme',23,28,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('vanilla',21,97,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('moo shu wrappers',21,3,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('wild rice',5,22,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('feta cheese',1,20,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('mozzarella',21,62,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('turkeys',16,83,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('onions',8,59,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('sea cucumbers',2,76,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('lettuce',8,80,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('huckleberries',7,17,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('cream',22,88,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('chambord',6,65,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('sesame seeds',15,5,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('celery',11,22,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('coconut oil',14,20,1);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('melons',3,91,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('butter',15,62,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('half-and-half',13,85,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('ricotta cheese',3,28,2);
INSERT INTO items (items.name, items.quantity, items.size, items.userid) VALUES ('peanuts',16,68,1);
